enum countriesTypes {
   FETCH_COUNTRIES = 'FETCH_COUNTRIES',
   FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR',
   SEARCH_COUNTRY_CHANGE = 'SEARCH_COUNTRY_CHANGE',
   SEARCH_COUNTRY_SUCCESS = 'SEARCH_COUNTRY_SUCCESS',
   SEARCH_COUNTRY_FAILED = 'SEARCH_COUNTRY_FAILED',
   SET_CURRENT_COUNTRY_CHANGE = 'SET_CURRENT_COUNTRY_CHANGE',
   SET_CURRENT_COUNTRY_SUCCESS = 'SET_CURRENT_COUNTRY_SUCCESS',
   SET_CURRENT_COUNTRY_FAILED = 'SET_CURRENT_COUNTRY_FAILED',
}

export { countriesTypes };
